name: Build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
  
    env:
      CC: gcc-12
      CXX: g++-12

    steps:
    - uses: actions/checkout@v4

    - name: Install gpg keys
      run: | 
        gpg --revc-keys A2C794A986419D8A
        gpg --lsign-keys A2C794A986419D8A
        gpg --finger A2C794A986419D8A

    - name: Makepkg Build and Check
      id: makepkg
      uses: edlanglois/pkgbuild-action@v1
