name: Build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
  
    env:
      CC: gcc-12
      CXX: g++-12

    steps:
    - uses: actions/checkout@v4

    - name: Makepkg Build and Check
      id: makepkg
      uses: edlanglois/pkgbuild-action@v1
      with:
        makepkgArgs: --skippgpcheck
