name: Build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
  
    env:
      CC: gcc-12
      CXX: g++-12

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install required packages
      run: |
        python -m pip install -U pip
        pip install -U build installer poetry setuptools wheel psutil recommonmark sphinx

    - name: Makepkg Build and Check
      id: makepkg
      uses: edlanglois/pkgbuild-action@v1
