name: Build

on: [push, workflow_dispatch]

jobs:
    build:
  runs-on: ubuntu-latest
      env:
        CC: gcc-12
        CXX: g++-12

    - name: Test exist clang.
      run: clang --version

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install required packages
      run: |
        sudo apt-get install -y zlib zstd libffi libedit ncurses libxml2-dev makepkg
        python -m pip install -U pip
        pip install -U setuptools wheel psutil recommonmark sphinx

    - name: Make packages
      run: makepkg